/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as SitesSiteIdBuildingsBuildingIdRouteImport } from './routes/sites.$siteId.buildings.$buildingId'
import { Route as SitesSiteIdBuildingsBuildingIdLinesLineIdRouteImport } from './routes/sites.$siteId.buildings.$buildingId.lines.$lineId'
import { Route as SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteImport } from './routes/sites.$siteId.buildings.$buildingId.lines.$lineId.workstations.$wsId'
import { Route as SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRouteImport } from './routes/sites.$siteId.buildings.$buildingId.lines.$lineId.workstations.$wsId.assets.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdBuildingsBuildingIdRoute =
  SitesSiteIdBuildingsBuildingIdRouteImport.update({
    id: '/buildings/$buildingId',
    path: '/buildings/$buildingId',
    getParentRoute: () => SitesSiteIdRoute,
  } as any)
const SitesSiteIdBuildingsBuildingIdLinesLineIdRoute =
  SitesSiteIdBuildingsBuildingIdLinesLineIdRouteImport.update({
    id: '/lines/$lineId',
    path: '/lines/$lineId',
    getParentRoute: () => SitesSiteIdBuildingsBuildingIdRoute,
  } as any)
const SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRoute =
  SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteImport.update({
    id: '/workstations/$wsId',
    path: '/workstations/$wsId',
    getParentRoute: () => SitesSiteIdBuildingsBuildingIdLinesLineIdRoute,
  } as any)
const SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRoute =
  SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRouteImport.update(
    {
      id: '/assets/$assetId',
      path: '/assets/$assetId',
      getParentRoute: () =>
        SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sites/$siteId': typeof SitesSiteIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId': typeof SitesSiteIdBuildingsBuildingIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sites/$siteId': typeof SitesSiteIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId': typeof SitesSiteIdBuildingsBuildingIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sites/$siteId': typeof SitesSiteIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId': typeof SitesSiteIdBuildingsBuildingIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteWithChildren
  '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId': typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sites/$siteId'
    | '/sites/$siteId/buildings/$buildingId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sites/$siteId'
    | '/sites/$siteId/buildings/$buildingId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId'
  id:
    | '__root__'
    | '/'
    | '/sites/$siteId'
    | '/sites/$siteId/buildings/$buildingId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId'
    | '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitesSiteIdRoute: typeof SitesSiteIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/buildings/$buildingId': {
      id: '/sites/$siteId/buildings/$buildingId'
      path: '/buildings/$buildingId'
      fullPath: '/sites/$siteId/buildings/$buildingId'
      preLoaderRoute: typeof SitesSiteIdBuildingsBuildingIdRouteImport
      parentRoute: typeof SitesSiteIdRoute
    }
    '/sites/$siteId/buildings/$buildingId/lines/$lineId': {
      id: '/sites/$siteId/buildings/$buildingId/lines/$lineId'
      path: '/lines/$lineId'
      fullPath: '/sites/$siteId/buildings/$buildingId/lines/$lineId'
      preLoaderRoute: typeof SitesSiteIdBuildingsBuildingIdLinesLineIdRouteImport
      parentRoute: typeof SitesSiteIdBuildingsBuildingIdRoute
    }
    '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId': {
      id: '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId'
      path: '/workstations/$wsId'
      fullPath: '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId'
      preLoaderRoute: typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteImport
      parentRoute: typeof SitesSiteIdBuildingsBuildingIdLinesLineIdRoute
    }
    '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId': {
      id: '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/sites/$siteId/buildings/$buildingId/lines/$lineId/workstations/$wsId/assets/$assetId'
      preLoaderRoute: typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRouteImport
      parentRoute: typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRoute
    }
  }
}

interface SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteChildren {
  SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRoute: typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRoute
}

const SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteChildren: SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteChildren =
  {
    SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRoute:
      SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdAssetsAssetIdRoute,
  }

const SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteWithChildren =
  SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRoute._addFileChildren(
    SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteChildren,
  )

interface SitesSiteIdBuildingsBuildingIdLinesLineIdRouteChildren {
  SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRoute: typeof SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteWithChildren
}

const SitesSiteIdBuildingsBuildingIdLinesLineIdRouteChildren: SitesSiteIdBuildingsBuildingIdLinesLineIdRouteChildren =
  {
    SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRoute:
      SitesSiteIdBuildingsBuildingIdLinesLineIdWorkstationsWsIdRouteWithChildren,
  }

const SitesSiteIdBuildingsBuildingIdLinesLineIdRouteWithChildren =
  SitesSiteIdBuildingsBuildingIdLinesLineIdRoute._addFileChildren(
    SitesSiteIdBuildingsBuildingIdLinesLineIdRouteChildren,
  )

interface SitesSiteIdBuildingsBuildingIdRouteChildren {
  SitesSiteIdBuildingsBuildingIdLinesLineIdRoute: typeof SitesSiteIdBuildingsBuildingIdLinesLineIdRouteWithChildren
}

const SitesSiteIdBuildingsBuildingIdRouteChildren: SitesSiteIdBuildingsBuildingIdRouteChildren =
  {
    SitesSiteIdBuildingsBuildingIdLinesLineIdRoute:
      SitesSiteIdBuildingsBuildingIdLinesLineIdRouteWithChildren,
  }

const SitesSiteIdBuildingsBuildingIdRouteWithChildren =
  SitesSiteIdBuildingsBuildingIdRoute._addFileChildren(
    SitesSiteIdBuildingsBuildingIdRouteChildren,
  )

interface SitesSiteIdRouteChildren {
  SitesSiteIdBuildingsBuildingIdRoute: typeof SitesSiteIdBuildingsBuildingIdRouteWithChildren
}

const SitesSiteIdRouteChildren: SitesSiteIdRouteChildren = {
  SitesSiteIdBuildingsBuildingIdRoute:
    SitesSiteIdBuildingsBuildingIdRouteWithChildren,
}

const SitesSiteIdRouteWithChildren = SitesSiteIdRoute._addFileChildren(
  SitesSiteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitesSiteIdRoute: SitesSiteIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
